# Generated by Django 2.2.5 on 2019-09-22 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='url',
        ),
    ]
