# Generated by Django 2.2.5 on 2019-09-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_note_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
